apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-11-07T16:01:57Z"
  name: aged-meadow
  uid: 022b373de5d34c80
spec:
  cpus: 1
  diskSize: 4GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 512MB
  network: {}
  ssh: true
  storage: {}
status:
  image:
    id: oci://docker.io/weaveworks/ignite-ubuntu@sha256:f8032a6738fdb372eb7e64734c9481f873b57e0ea72b610e0189f0a329283173
    size: 237539766B
  ipAddresses:
  - 10.61.0.6
  kernel:
    id: oci://docker.io/weaveworks/ignite-kernel@sha256:18ee1005bb3881faf09059038eca8b298d9d7598cde675c4a900e275fe0a2454
    size: 51377512B
  running: true
  runtime:
    id: ignite-022b373de5d34c80
  startTime: "2019-11-07T16:01:57Z"
